name: generate

on: [push]

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Source Code
              uses: actions/checkout@v4

            - uses: actions/setup-node@v4
              with:
                node-version: 'latest'        
                
            - run: npm ci

            - run: node generate.js

            - name: Create key File
              run: |
                echo "export default '${{ secrets.API_KEY }}';" > src/data.ts

