name: generate

on: [push]

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Source Code
              uses: actions/checkout@v3

            - name: Create key File
              run: |
                echo "export default '${{ secrets.API_KEY }}';" > ./data.json

            - name: Deploy to GitHub Pages
              uses: JamesIves/github-pages-deploy-action@v4
              with:
                    branch: main
